name: Build and Deploy (Dispatch)
on:
 push:
   branches:
     - master

jobs:
  release-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CLOUD_DEVOPS_TOKEN  }}
          repository: ${{ secrets.dispatch_repo }}
          event-type: release
